[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.curl"]

[phases.build]
cmds = ["mkdir -p data users src templates api analytics includes", "chmod 755 data users src templates api analytics includes", "touch users/users.json", "echo '[]' > users/users.json"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
